import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import Link from "next/link";
import LayoutNav from "@/components/layout/nav";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/site.webmanifest"></link>
        <CookiesProvider>
          <header className="bg-white border-b">
            <nav className="max-w-6xl mx-auto px-4 lg:px-0 py-4 flex items-center justify-between">
              <div>
                <Link href={"/"}>
                  <h3 className="text-lg lg:text-2xl font-semibold text-black hover:text-red-600">
                    Expense Tracker
                  </h3>
                </Link>
              </div>
              <LayoutNav />
            </nav>
          </header>
          <main className="max-w-6xl mx-auto py-6 px-6 lg:px-0">
            {children}
          </main>
          <footer></footer>
          <Toaster />
        </CookiesProvider>
      </body>
    </html>
  );
}
